# Generated by Django 3.2.7 on 2023-04-29 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='consult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('did', models.CharField(max_length=150)),
                ('uid', models.CharField(max_length=150)),
                ('date', models.CharField(max_length=150)),
                ('des', models.CharField(max_length=150)),
                ('status', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=150)),
                ('age', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=150)),
                ('specialization', models.CharField(max_length=150)),
                ('experience', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('genericname', models.CharField(max_length=150)),
                ('dosage', models.CharField(max_length=150)),
                ('form', models.CharField(max_length=150)),
                ('manufature', models.CharField(max_length=150)),
                ('expdate', models.CharField(max_length=150)),
                ('price', models.CharField(max_length=150)),
                ('image', models.CharField(max_length=150)),
                ('qty', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='drug_req',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('genericname', models.CharField(max_length=150)),
                ('dosage', models.CharField(max_length=150)),
                ('form', models.CharField(max_length=150)),
                ('manufature', models.CharField(max_length=150)),
                ('did', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=150)),
                ('pid', models.CharField(max_length=150)),
                ('price', models.CharField(max_length=150)),
                ('qty', models.CharField(max_length=150)),
                ('cardname', models.CharField(max_length=150)),
                ('cardnumber', models.CharField(max_length=150)),
                ('cvv', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=150)),
                ('age', models.CharField(max_length=150)),
            ],
        ),
    ]
