# Generated by Django 3.2.7 on 2023-05-19 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consult',
            name='file',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consult',
            name='medicine',
            field=models.CharField(default=2, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consult',
            name='prescription',
            field=models.CharField(default=4, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drug_req',
            name='status',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
    ]
