# Generated by Django 3.2.7 on 2023-05-19 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_auto_20230519_1523'),
    ]

    operations = [
        migrations.CreateModel(
            name='drug_interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine', models.CharField(max_length=150)),
                ('nonmedicine', models.CharField(max_length=150)),
            ],
        ),
    ]
